workspace:
  base: /base
pipeline:
  build:
    image: hgarcio/alpine-node-java
    commands:
     - mkdir node node_modules $HOME/.m2
     - npm cache clean
     - npm install -g bower gulp-cli
     - npm --version
     - node --version
     - java -version
     - bower -v
     - gulp -v
     - chmod +x mvnw
     - npm install
     - ./mvnw clean
     - ./mvnw package -Pprod -DskipTests > /base/out.txt
  logs:
    image: alpine
    commands:
     - apk update && apk add --no-cache openssh sshpass
     - cd /base
     - ls
     - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no out.txt root@144.217.80.5:/root/out.txt
    when:
        status:  [ failure,success ]