pipeline:
  build:
    image: hgarcio/java-node
    commands:
     - yarn global add npm@6.2.0
     - npm cache clean --force
     - npm install -g bower gulp-cli
     - chmod +x mvnw
     - npm install
     - ./mvnw clean
     - ./mvnw package -Pprod -DskipTests

    # - npm install -g bower gulp-cli
     #- npm install > /base/npminstall.txt
  #logs:
  #  image: alpine
  #  commands:
  #   - apk update && apk add --no-cache openssh sshpass
  #   - cd /base
  #   - ls
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no npminstall.txt root@144.217.80.5:/root/npminstall.txt
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no mvwpackage.txt root@144.217.80.5:/root/mvwpackage.txt
  #  when:
  #      status:  [ failure ]