pipeline:
  build:
    image: ubuntu:16.04
    commands:
     - apt-get update
     - apt-get install software-properties-common python-software-properties
     - add-apt-repository ppa:webupd8team/java
     - apt-get update
     - apt-get install oracle-java8-installer
     - apt-get install oracle-java8-set-default
     - java -version

    # - npm install -g bower gulp-cli
     #- npm install > /base/npminstall.txt
  #logs:
  #  image: alpine
  #  commands:
  #   - apk update && apk add --no-cache openssh sshpass
  #   - cd /base
  #   - ls
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no npminstall.txt root@144.217.80.5:/root/npminstall.txt
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no mvwpackage.txt root@144.217.80.5:/root/mvwpackage.txt
  #  when:
  #      status:  [ failure ]