workspace:
  base: /base
pipeline:
  build:
    image: hgarcio/alpine-node-java
    commands:
     - npm cache clean
     - npm install -g npm
     - npm --version
    # - npm install -g bower gulp-cli
     #- npm install > /base/npminstall.txt
  logs:
    image: alpine
    commands:
     - apk update && apk add --no-cache openssh sshpass
     - cd /base
     - ls
     - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no npminstall.txt root@144.217.80.5:/root/npminstall.txt
     - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no mvwpackage.txt root@144.217.80.5:/root/mvwpackage.txt
    when:
        status:  [ failure ]