pipeline:
  build:
    image: ubuntu:16.04
    commands:
     - apt-get -y update
     - apt-get -y install software-properties-common python-software-properties
     - add-apt-repository -y  ppa:webupd8team/java
     - apt-get -y update
     - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
     - apt-get install -y oracle-java8-installer
     - java -version
     - wget https://nodejs.org/dist/v6.11.3/node-v6.11.3-linux-x64.tar.g‌​z
     - mkdir -p /opt/nodejs
     - tar -xvzf node-v6.11.3-linux-x64.tar.gz -C /opt/nodejs/
     - mv node-v6.11.3-linux-x64 6.11.3
     - cd /opt/nodejs
     - ln -s 6.11.3 current
     - ln -s /opt/nodejs/current/bin/node /bin/node
     - node -v

    # - npm install -g bower gulp-cli
     #- npm install > /base/npminstall.txt
  #logs:
  #  image: alpine
  #  commands:
  #   - apk update && apk add --no-cache openssh sshpass
  #   - cd /base
  #   - ls
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no npminstall.txt root@144.217.80.5:/root/npminstall.txt
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no mvwpackage.txt root@144.217.80.5:/root/mvwpackage.txt
  #  when:
  #      status:  [ failure ]