pipeline:
  jhipster-registry:
    image: jhipster/jhipster-registry:v3.0.3
    detach: true
    volumes:
        - /home/ubuntu/drone/container-volumes/central-center-config:/central-config
    environment:
        - SPRING_SECURITY_USER_PASSWORD:hgarcia
  build:
    image: hgarcio/ubuntu-node-java
    commands:
     - ./mvnw clean
     - ./mvnw package -Pprod DskipTests
    # - npm install -g bower gulp-cli
     #- npm install > /base/npminstall.txt
  #logs:
  #  image: alpine
  #  commands:
  #   - apk update && apk add --no-cache openssh sshpass
  #   - cd /base
  #   - ls
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no npminstall.txt root@144.217.80.5:/root/npminstall.txt
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no mvwpackage.txt root@144.217.80.5:/root/mvwpackage.txt
  #  when:
  #      status:  [ failure ]