pipeline:
  jhipster-registry:
    image: jhipster/jhipster-registry:v3.0.3
    detach: true
    volumes:
        - /home/ubuntu/drone/container-volumes/central-center-config:/central-config
    environment:
        - SPRING_SECURITY_USER_PASSWORD:hgarcia
  build:
    image: ubuntu:16.04
    commands:
     - apt-get -y update
     - apt-get -y install software-properties-common python-software-properties
     - add-apt-repository -y  ppa:webupd8team/java
     - apt-get -y update
     - echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections
     - apt-get install -y oracle-java8-installer
     - java -version
     - apt-get install curl
     - curl -sL https://deb.nodesource.com/setup_6.x | bash
     - apt-get install -y nodejs
     - node -v
     - npm install npm --global
     - npm -v
     - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
     - echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
     - apt-get -y update
     - apt-get install -y yarn
     - apt-get install -y bzip2
     - npm install -g bower gulp-cli
     - chmod +x mvnw
     - npm install
     - ./mvnw clean
     - ./mvnw package -Pdrone
     - ls
    # - npm install -g bower gulp-cli
     #- npm install > /base/npminstall.txt
  #logs:
  #  image: alpine
  #  commands:
  #   - apk update && apk add --no-cache openssh sshpass
  #   - cd /base
  #   - ls
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no npminstall.txt root@144.217.80.5:/root/npminstall.txt
  #   - sshpass -p 'Cj57AQCn' scp -o StrictHostKeyChecking=no mvwpackage.txt root@144.217.80.5:/root/mvwpackage.txt
  #  when:
  #      status:  [ failure ]