pipeline:
  build-node:
    image: node:6
    commands:
     - npm install -g npm
     - npm install -g bower gulp-cli
  build-java:
    image: openjdk:8
    commands:
     - ./mvnw clean
     - ./mvnw package -Pprod -DskipTests
  docker:
    image: plugins/docker
    username: hgarcio
    password: h1o2g3o4o5o6
    repo: hgarcio/gtwhatcc
    tags: latest