pipeline:
  backup-mysql-data:
    image: alpine
    commands:
      - apk update && apk add --no-cache openssh sshpass
      - export SSHPASS=Cj57AQCn
      - sshpass -e ssh -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca 'tar -czvf /home/ubuntu/mysql.tar.gz /home/ubuntu/ambientes/dev/data/mysql'
  copying-mysql-data:
    image: alpine
    commands:
      - apk update && apk add --no-cache openssh sshpass
      - cd /workspace
      - rm -rf /workspace/*
      - export SSHPASS=Cj57AQCn
      - sshpass -e scp -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca:/home/ubuntu/mysql.tar.gz mysql.tar.gz 
      - tar -xzvf mysql.tar.gz
      - ls
      - mv home/ubuntu/ambientes/dev/data/mysql mysql-v
      - mv mysql-v/* .
      - rm -rf home
      - ls
      - sshpass -e ssh -o StrictHostKeyChecking=no root@vps135621.vps.ovh.ca 'rm -rf /home/ubuntu/mysql.tar.gz'
    volumes:
      - workspace-drone-mysql:/workspace
  mysql:
   image: mysql:5.7
   volumes:
      - workspace-drone-mysql:/var/lib/mysql
   detach: true
  build:
    image: hgarcio/ubuntu-node-java
    commands:
     - chmod +x mvnw
     - ./mvnw clean install
     - ./mvnw package -Dspring.profiles.active=test
  docker:
    image: plugins/docker
    username: hgarcio
    password: h1o2g3o4o5o6
    auto_tag: true
    repo: hgarcio/gtwhatcc
    dockerfile: Dockerfile
    tags: latest