pipeline:
  build-node:
    image: openjdk:8-jre-alpine
    commands:
     - npm install -g bower gulp-cli
  build-cosa:
    image: sickp/alpine-node:6.11.3-r1
    commands:
     - npm install -g bower gulp-cli
