language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  - NODE_VERSION=4.4.7
addons:
    apt:
        packages:
            - sshpass
script:
  - ./mvnw clean
  - ./mvnw package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_success:
    - mkdir build
    - mv * build
    - tar -czf gtw.tgz build
    - export SSHPASS=$pass
    - echo $path
    - sshpass -e scp package.tgz $user@$host:$path
