language: java
jdk:
  - oraclejdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  - NODE_VERSION=4.4.7
addons:
    apt:
        packages:
            - sshpass
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm
  - npm install -g bower gulp-cli
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
  - chmod +x mvnw
  - chmod +x deploy.sh
install: npm install
script:
  - ./mvnw clean
  - ./mvnw package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
after_success:
    - cd target
    - echo 
    - tar -cf gtw.tgz *.war
    - export SSHPASS=$DEPLOY_PASS
    - sshpass -e scp -o StrictHostKeyChecking=no gtw.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH/$TRAVIS_BRANCH/deploy/gtw
